Newbinary
HE-Arc/livre-python pull request #149
Opened 2017-06-01 07:58 UTC by SchnaebeleMarc

2017-06-01 08:02 UTC, greut requested changes
```
source/binary/examples/memoryview_ex_python.py:3:3: E227 missing whitespace around bitwise or shift operator

source/binary/examples/memoryview_ex_python.py:3:7: E225 missing whitespace around operator

source/binary/examples/memoryview_ex_python.py:14:3: E225 missing whitespace around operator

source/binary/examples/memoryview_ex_python.py:14:5: E225 missing whitespace around operator

source/binary/examples/memoryview_ex_python.py:14:7: E225 missing whitespace around operator

source/binary/examples/memoryview_ex_python.py:19:7: E225 missing whitespace around operator

source/binary/examples/struct.py:3:3: E227 missing whitespace around bitwise or shift operator

source/binary/examples/struct.py:3:7: E225 missing whitespace around operator

source/binary/examples/struct.py:4:1: E402 module level import not at top of file

source/binary/examples/struct.py:5:1: E402 module level import not at top of file

source/binary/examples/struct.py:7:3: E225 missing whitespace around operator

source/binary/examples/struct.py:7:5: E225 missing whitespace around operator

source/binary/examples/struct.py:7:7: E225 missing whitespace around operator

source/binary/examples/struct.py:9:1: E402 module level import not at top of file

source/binary/examples/struct.py:10:1: E402 module level import not at top of file

source/binary/examples/struct.py:13:7: E225 missing whitespace around operator

source/binary/examples/struct.py:26:3: E227 missing whitespace around bitwise or shift operator

source/binary/examples/struct.py:26:7: E225 missing whitespace around operator

source/binary/examples/struct.py:28:3: E225 missing whitespace around operator

source/binary/examples/struct.py:28:5: E225 missing whitespace around operator

source/binary/examples/struct.py:28:7: E225 missing whitespace around operator

source/binary/examples/struct.py:30:7: E225 missing whitespace around operator
```

La branche ne semble pas à jour.

2017-06-01 08:55 UTC, SchnaebeleMarc commented
Pourquoi le See review de greut me montre toujours les mêmes erreurs alors qu'elles sont corrigées ! et l'erreur de Travis indiqué n'est pas dans un de mes documents...

2017-06-01 10:15 UTC, greut commented
```
source/binary/examples/byte_inst.py:8:1: W391 blank line at end of file

source/binary/examples/bytearray.py:22:1: W391 blank line at end of file

source/binary/examples/bytearray_cast.py:9:1: W391 blank line at end of file

source/binary/examples/cast_bytes_int.py:28:1: W391 blank line at end of file

source/binary/examples/cast_bytes_string.py:11:1: W391 blank line at end of file

source/binary/examples/lecture_fichier.py:14:1: W391 blank line at end of file

source/binary/examples/memoryview_ex_bytearray.py:10:1: W391 blank line at end of file

source/binary/examples/memoryview_inst.py:6:1: W391 blank line at end of file

source/binary/examples/memoryview_op.py:20:1: W391 blank line at end of file
```

2017-06-01 12:15 UTC, greut reviewed
Des détails de merge et d'intersphinx. Merci.

2017-06-01 12:15 UTC, greut commented on source/binary/index.rst
>  `Un tableau résumant les opérations standards sur les bytes se trouve sur la documentation officielle <https://docs.python.org/3.1/library/stdtypes.html>`_.
faites un lien intersphinx ce qui évitera de pointer sur la version 3.1.

2017-06-01 12:15 UTC, greut commented on source/binary/index.rst
> +`Plus d'opérations ici <https://docs.python.org/3.1/library/stdtypes.html>`_.
idem.

2017-06-01 12:15 UTC, greut commented on source/index.rst
> +====================
Ne touchez pas à ce fichier-là, merci.

2017-06-01 12:15 UTC, greut commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
idem.

2017-06-01 14:03 UTC, SchnaebeleMarc commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
Built-in Types est une classe ou un module?
J'ai essayé intersphinx en changeant à chaque fois mod et class avec les noms suivant:
_bltin-types
bltin-types
stdtypes
built-in types 

à chaque fois la cible n'est pas trouvée.

J'ai également essayé avec la "nouvelle" syntaxe par exemple: 
:ref:`built-in types <python:built-in types>`

Mais rien a faire...

2017-06-01 14:17 UTC, greut commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
Alors alors, soit c'est une classe, une fonction, etc. et on utilise `:py:class:`,`:py:meth:`, etc..

Soit, ce n'est rien de tout ça, et on va rechercher une référence. `:ref:...`

Pour trouver la référence:
1. Ouvrir la documentation
2. Trouver le lien _Show Source_
3. Rechercher une référence `.. _xyz:`

2017-06-01 14:21 UTC, greut commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
e.g. https://github.com/HE-Arc/livre-python/blob/master/source/builtins/index.rst

2017-06-01 15:11 UTC, SchnaebeleMarc commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
La référence est surement : .. _bltin-types:
Quelle sorte de lien dois-je chercher et qu'entendez-vous par show source ?
Faut-il que je trouve un lien en inspectant la page web ?  
Ensuite une fois ces informations trouvées dans le :ref: quel ordre doivent prendre les arguments?
Par exemple :ref: lien <python:ref>

De plus je ne comprends pas pourquoi changer, car si j'utilise une référence sur le site de la documentation python cela revient au même que ce que je fais avec : 
`Plus d'opérations ici <https://docs.python.org/3.1/library/stdtypes.html>`_.
Car le lien sera fixe donc autant changer la version sur laquelle je pointe :
`Plus d'opérations ici <https://docs.python.org/3.6/library/stdtypes.html>`_.

Ou alors je ne comprends rien comme d'habitude ^^'

2017-06-01 15:18 UTC, greut commented on source/binary/index.rst
> +`<https://docs.python.org/3.1/library/stdtypes.html>`_
1. Ouvrir la documentation **dans son navigateur préféré**
2. Trouver le lien _Show Source_ avec **Ctrl-f**
3. Cliquer sur le lien avec sa souris
4. Rechercher une référence `.. _xyz:`
5. Regardez comment les autres ont fait

Le lien vers 3.6 est référencé une seule fois, dès qu'on passera à 3.7 il suffira d'adapter ce lien dans `conf.py` et non dans tous les fichiers.

2017-06-01 21:40 UTC, greut commented on source/binary/index.rst
> +
?

2017-06-01 21:40 UTC, greut commented on source/binary/index.rst
>  `<http://docs.python-guide.org/en/latest/scenarios/json/>`_
Vous êtes sûr de vous, concernant `json`?

2017-06-02 11:19 UTC, greut commented on source/binary/index.rst
> +Un :py:mod:`struct` permet de convertir des structures C en valeurs Python représenté sous forme d'objets bytes. Ceux-ci sont utilisés pour manipuler des données binaire depuis des fichiers, le résea
En C, ça se nomme `packing`/`unpacking`: http://www.catb.org/esr/structure-packing/

2017-06-02 11:20 UTC, greut requested changes
`source/index.rst` a encore des modifications par rapport à la branche *master*

2017-06-02 12:17 UTC, SchnaebeleMarc commented
C'est pas le fichier que je ne dois pas toucher justement?

2017-06-02 12:44 UTC, greut commented
@SchnaebeleMarc que vous ne *deviez* pas toucher. Il faut annuler les modifs faites à présent.

2017-06-04 17:15 UTC, greut approved these changes

2017-06-04 17:15 UTC, merged

2017-06-22 09:42 UTC, greut commented on source/binary/index.rst
> -
:crying_cat_face: