commit test
HE-Arc/livre-python pull request #15
Opened 2017-03-09 08:18 UTC by JonathanGuerne

2017-03-09 09:08 UTC, JonathanGuerne commented
pull request pour documenter la librairie invoke

2017-03-09 09:10 UTC, greut commented
Il y a pas mal de choses en trop ici.

2017-03-16 11:59 UTC, greut requested changes

2017-03-16 11:59 UTC, greut commented on README.rst
> +
ceci.

2017-03-16 11:59 UTC, greut commented on source/invoke/examples/example.py
> +    json.dump(data, fp, sort_keys=True, indent=4)
celà

2017-03-16 12:00 UTC, greut commented
Tous ces merges, c'est la jungle. Faites un rebase.

```
$ git fetch origin
$ git rebase origin/master
$ ...
$ git push -f jonathan test
```

2017-03-18 16:38 UTC, greut commented
ok 84fddd1

Et j'ai opéré un peu de nettoyage : 47cdb6b

2017-03-18 16:38 UTC, closed without merging