Multiprocessing
HE-Arc/livre-python pull request #150
Opened 2017-06-01 15:05 UTC by Gandus10

Modification de mon fichier par rapport aux commentaires de M. Blanc

2017-06-01 15:15 UTC, greut requested changes
Vous balayez plein de commentaires du revers de la main.

Okay pour que vous ne les adressiez que un seul à la fois, mais laissez les commentaires. Sait-on jamais.

2017-06-01 15:15 UTC, greut commented on source/multiprocessing/index.rst
> +Bien que la plupart des CPUs modernes comportent plusieurs coeurs, le code que l’on écrit doit aussi être formatté adéquatement afin d’en tirer pleinement avantage.[#Ref]_
en mode citation c'est bien, étant donné que c'est un copier-coller.

2017-06-01 15:15 UTC, greut commented on source/multiprocessing/index.rst
> +Le Global Interpreter Lock est un algorithme qui gère l'exécution de plusieurs threads dans un programme Python. la connaissance du GIL est indispensable lorsque vous travaillez avec plusieurs thread
Vous tirez ça d'où?

2017-06-01 15:15 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
_hint_

2017-06-01 15:15 UTC, greut commented on source/multiprocessing/index.rst
> +Par Gander Laurent
laissez ceci ainsi.

2017-06-06 08:32 UTC, Gandus10 commented
Les changes requested ont été faits, y aurait-il un autre problème pour que le merge ne sois pas fais ?

2017-06-06 09:09 UTC, greut commented on source/multiprocessing/index.rst
> +Par Gander Laurent
@Gandus10 ceci.

2017-06-06 09:11 UTC, greut commented on source/multiprocessing/index.rst
> +.. warning:: la méthode recv() efface les données qu'elle recoit, ce qui peut être un problème de sécurité, c'est pourquoi vous devriez utiliser une authentification avant d'utiliser les métodes recv
vous ajoutez des typos dans mes commentaires? Scandale.

e97fc8c1c4c7cb18aa588df0b15630081643cf93

2017-06-06 09:12 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
!!

2017-06-06 09:12 UTC, greut commented on source/multiprocessing/index.rst
> +
c'est possible de formatter ça autrement qu'un texte _normal_ ?

2017-06-06 09:13 UTC, greut requested changes
Passez en revue les commentaires.

2017-06-06 09:15 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
https://docs.python.org/3.6/glossary.html#term-global-interpreter-lock

2017-06-06 09:17 UTC, greut commented
@Gandus10 et un _rebase_ car vous avez fait un _merge_.

2017-06-06 09:18 UTC, Gandus10 commented
Merci beaucoup d'avoir répondu aussi vite, je prends bonne note de vos recommandations

2017-06-06 09:20 UTC, greut commented
Le but de l'exercice est que vous soyez capable de continuer **à partir de mes commentaires et corrections** et non de tout virer pour revenir à la version antérieure.

2017-06-06 09:24 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
Le cas _thread-safe_ non _thread-safe_ est plus compliqué que ça. Mais ce n'est pas ce problème qui est adressé par `multiprocessing`.

2017-06-06 09:25 UTC, Gandus10 commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
D'accord

2017-06-06 09:33 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
le `GIL` impose qu'en pratique un seul cœur ne travaille à la fois. Même en utilisant les _threads_.

- http://www.dabeaz.com/GIL/gilvis/
- https://www.youtube.com/watch?v=Obt-vMVdM8s#t=19m30

2017-06-06 09:36 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
Le **tl;dr** concernant `multiprocessing` est:

- Python est très mauvais pour faire du multi-threading (à la Java, classique) à cause du GIL.
- Solutions:
    - faire de l'asynchrône (un seul _thread_) avec `asyncio`
    - utiliser plusieurs processus Python (possédant chacun sa mémoire dédiée) avec `multiprocessing`

2017-06-06 09:42 UTC, greut commented on source/multiprocessing/index.rst
> -.. attention:: Dire que Python n'est pas thread-safe est faux. Python peut utiliser les threads du système (pthread).
https://en.wikipedia.org/wiki/CPython#Design

2017-06-06 14:49 UTC, greut commented on source/multiprocessing/index.rst
> +===============
laissez comme c'était.

2017-06-06 14:49 UTC, greut commented on source/multiprocessing/index.rst
> +Dans le main, nous appelons la fonction info puis nous créons un objet Process avec comme arguments 'target = f' qui est la fonction que le processus éxecutera et les arguments de la fonction 'args=(
_exécutera_, il n'y a pas d'accent aigu devant un _x_

2017-06-06 14:50 UTC, greut commented on source/multiprocessing/index.rst
> +Dans le main, nous appelons la fonction info puis nous créons un objet Process avec comme arguments 'target = f' qui est la fonction que le processus éxecutera et les arguments de la fonction 'args=(
:warning: `('bob') == 'bob'`

2017-06-06 14:51 UTC, greut commented on source/multiprocessing/index.rst
> +.. warning:: Si un processus est "tué", les données risquent d'être corrompu dans la queue, ce qui signifie qu'un autre processus qui tenterait d'acceder à la file queue risquerait de soulever une ex
pourquoi comment?

2017-06-06 14:51 UTC, greut commented on source/multiprocessing/index.rst
> -.. Vous mélangez des choses ici... Il n'y a aucun lien entre l'authentificiation et l'accès concurrent à recv. Dans la documentation officielle, ce sont deux warnings séparés.
ceci.

2017-06-06 14:52 UTC, greut commented on source/multiprocessing/index.rst
> +    Synchronisation  : https://docs.python.org/3/library/multiprocessing.html#synchronization-primitives
Utilisez `ref`

2017-06-06 14:52 UTC, greut commented on source/multiprocessing/index.rst
> +    Synchronisation  : https://docs.python.org/3/library/multiprocessing.html#synchronization-primitives
ou virez.

2017-06-06 15:21 UTC, greut commented on source/multiprocessing/index.rst
> -
ceci.

2017-06-06 18:53 UTC, Gandus10 commented on source/multiprocessing/index.rst
> +.. warning:: Si un processus est "tué", les données risquent d'être corrompu dans la queue, ce qui signifie qu'un autre processus qui tenterait d'acceder à la file queue risquerait de soulever une ex
Une question d'exit handlers  ? 
https://docs.python.org/3/library/atexit.html

2017-06-06 19:18 UTC, greut commented on source/multiprocessing/index.rst
> +.. warning:: Si un processus est "tué", les données risquent d'être corrompu dans la queue, ce qui signifie qu'un autre processus qui tenterait d'acceder à la file queue risquerait de soulever une ex
Un `atexit` permet de capturer ce qu'il se passe lors d'un `kill` sous UN*X.

Si vous ne comprenez pas ce que vous écrivez/traduisez, ne le mettez pas **ou** cherchez à comprendre.

Au passage, un autre article: https://jeffknupp.com/blog/2013/06/30/pythons-hardest-problem-revisited/

2017-06-07 08:14 UTC, greut commented on source/multiprocessing/index.rst
> +==================
on y est presque.

2017-06-07 08:16 UTC, greut commented on source/multiprocessing/index.rst
> +Multiprocessing de python permet d'utiliser un ensemble de processus qui consumeront une liste de tâches contenue dans une :py:mod:`queue`.
Il y a plusieurs `queue` en Python.
- https://docs.python.org/3/library/queue.html
- https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues
- https://docs.python.org/3/library/asyncio-queue.html

C'est la deuxième.

2017-06-07 08:20 UTC, greut commented on source/multiprocessing/index.rst
> +Un exemple est que cela peut prendre plus de temps pour deux threads d'appeler la même fonction qu'un thread appelant deux fois la fonction. [#Ref2]_
Le _GIL_ est un verrou (_lock_) que l'interpréteur demande afin d'être _thread-safe_ sur les types primitifs. C'est lié au fait que le ramasse-miette de Python est utilise le comptage des références.

- CPython, C++ (_smart pointers_), PHP, Perl, ...: https://en.wikipedia.org/wiki/Reference_counting
- JVM, CLR, PyPy: https://en.wikipedia.org/wiki/Tracing_garbage_collection

2017-06-07 08:22 UTC, greut commented on source/multiprocessing/index.rst
> +Dans le main, nous appelons la fonction info puis, nous créons un objet Process avec comme arguments 'target = f' qui est la fonction que le processus exécutera et les arguments de la fonction 'args=
:warning: `('bob') != ('bob',)`

2017-06-07 08:23 UTC, greut commented on source/multiprocessing/index.rst
> +La classe Pipe permet aussi la création d'un canal entre deux processus. Le constructeur du pipe retourne deux objets de connection qui sont l'entrée et la sortie du canal.
Quelles différences avons-nous entre un `Pipe` et une `Queue` du coup ?

2017-06-07 08:24 UTC, greut commented on source/multiprocessing/index.rst
> +            os.fork() est utilisé par le processus parent pour fork l'interpreteur Python. Quand le processus enfant est lancé, ses ressources sont identiques au processus parent. :fork: est disponib
> :fork: est disponible uniquement sur Linux.

Est-ce bien ce que dit la doc?

2017-06-07 08:26 UTC, greut commented on source/multiprocessing/index.rst
> +
> C'est pourquoi, on utilise plutôt le module multiprocessing

Si c'est un problème dont le CPU est le facteur limitant. Si notre problème est limité par les entrées-sorties (la mémoire), alors les _threads_ ou `asyncio` devraient faire l'affaire.

2017-06-07 08:27 UTC, greut commented on source/multiprocessing/index.rst
> +.. [#Pipe] https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe
`:py:class:multiprocessing.Pipe`

2017-06-07 08:28 UTC, greut commented on source/multiprocessing/index.rst
> +.. [#Synchronisation] https://docs.python.org/3/library/multiprocessing.html#synchronization-primitives
On ne peut pas faire mieux... il n'y a pas de référence dans la doc. 😞 

https://raw.githubusercontent.com/python/cpython/3.6/Doc/library/multiprocessing.rst

2017-06-07 08:36 UTC, greut commented on source/multiprocessing/index.rst
> +    On peut partager de la mémoire en utilisant les classes :py:class:`multiprocessing.Value` ou :py:class:`multiprocessing.Array`.
`Value` n'est pas une classe...

```rst
.. function:: Value(typecode_or_type, *args, lock=True)
```

https://raw.githubusercontent.com/python/cpython/3.6/Doc/library/multiprocessing.rst

2017-06-07 08:56 UTC, Gandus10 commented on source/multiprocessing/index.rst
> +Dans le main, nous appelons la fonction info puis, nous créons un objet Process avec comme arguments 'target = f' qui est la fonction que le processus exécutera et les arguments de la fonction 'args=
Je suis d'accord avec vous, c'est pourquoi j'ai changé dans l'exemple du process.py

2017-06-07 09:47 UTC, greut commented on source/multiprocessing/index.rst
> +Multiprocessing de python permet d'utiliser un ensemble de processus qui consumeront une liste de tâches contenue dans une :py:mod:`simplequeue`.
nah... `multiprocessing.Queue`

2017-06-07 09:48 UTC, greut commented on source/multiprocessing/index.rst
> +            Quand le programme est lancé et lance la méthode forkserver.start(), depuis ce moment, chaque fois qu'un processus est nécessaire, un processus est demandé au serveur par le processus par
_GNU's Not Unix_ ;-)

2017-06-07 09:48 UTC, greut commented on source/multiprocessing/index.rst
> +    .. function:: Array(typecode_or_type, *args, lock=True)
.... `:py:func:multiprocessing.Value`

2017-06-07 09:49 UTC, greut commented on source/multiprocessing/index.rst
> +    Un objet renvoyé par la classe Manager() contrôle un serveur de processus qui contient des objets Python et permet à d'autres processus de les manipuler à l'aide de proxies.
??

2017-06-07 09:59 UTC, greut commented on source/multiprocessing/index.rst
> +Dans le main, nous appelons la fonction info puis, nous créons un objet Process avec comme arguments 'target = f' qui est la fonction que le processus exécutera et les arguments de la fonction 'args=
Et pas ici?

2017-06-07 09:59 UTC, greut commented on source/multiprocessing/index.rst
> +La classe Pipe permet aussi la création d'un canal entre deux processus. Le constructeur du pipe retourne deux objets de connection qui sont l'entrée et la sortie du canal.
conne*x*ion

2017-06-07 10:00 UTC, greut commented on source/multiprocessing/index.rst
> +Un exemple est que cela peut prendre plus de temps pour deux threads d'appeler la même fonction qu'un thread appelant deux fois la fonction. [#Ref2]_
> Le Global Interpreter Lock est un verrou (lock) que l'interpréteur demande afin d'être thread-safe
> [...]
> car la gestion de la mémoire de CPython n'est pas thread-safe.

Je suis confus.

2017-06-07 10:00 UTC, greut commented on source/multiprocessing/index.rst
>  ===================
toujours...

2017-06-07 10:25 UTC, Gandus10 commented on source/multiprocessing/index.rst
> +Multiprocessing de python permet d'utiliser un ensemble de processus qui consumeront une liste de tâches contenue dans une :py:mod:`simplequeue`.
Sphinx n'est pas censé m'avertir pour les erreurs de ce type ?

2017-06-07 10:29 UTC, greut commented on source/multiprocessing/index.rst
> +Multiprocessing de python permet d'utiliser un ensemble de processus qui consumeront une liste de tâches contenue dans une :py:mod:`simplequeue`.
Il va vous dire si ça existe ou non. Il ne peut pas vous dire c'est correct par rapport au contexte dans lequel se trouve ce lien.

En fait, vous pouvez virer la deuxième partie de la phrase à partir de _qui_.

2017-06-07 10:33 UTC, greut commented on source/multiprocessing/index.rst
> +Bien que la plupart des CPUs modernes comportent plusieurs coeurs, le code que l’on écrit doit aussi être formatté adéquatement afin d’en tirer pleinement avantage. [#Ref1]_
Laissez l'indentation qui montrer que c'est une citation `blockquote`.

2017-06-07 10:35 UTC, greut commented on source/multiprocessing/index.rst
> +Multiprocessing de python permet d'utiliser un ensemble de processus qui consumeront une liste de tâches contenue dans une :py:class:`multiprocessing.SimpleQueue`.
Le sens de consumer en français n'est pas tout à fait le même.

La liste de tâches c'est un cas particulier de l'usage de `multiprocessing` et pas une généralité. Ôtez-le.

2017-06-07 10:37 UTC, greut commented on source/multiprocessing/index.rst
> +La différence entre Pipe et Queue est qu'un pipe ne peut avoir que deux extrémités alors que la Queue peut avoir plusieurs consommateurs et plusieurs producteurs.
> For passing messages one can use Pipe() (for a connection between two processes) or a queue (which allows multiple producers and consumers).
>
> https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues

Reste à comprendre et traduire correctement.

Ou pas.

2017-06-07 10:40 UTC, greut commented
Dès que le build passe, je merge... je perds patience.

2017-06-07 10:42 UTC, greut approved these changes

2017-06-07 11:22 UTC, greut commented on source/multiprocessing/index.rst
> +La différence entre Pipe et Queue est qu'un pipe ne peut avoir qu'une connexion entre deux precessus alors que la Queue peut avoir plusieurs consommateurs et plusieurs producteurs.
e -> o

2017-06-07 11:23 UTC, greut commented on source/multiprocessing/index.rst
> +La différence entre Pipe et Queue est qu'un pipe ne peut avoir qu'une connexion entre deux precessus alors que la Queue peut avoir plusieurs consommateurs et plusieurs producteurs.
un Pipe est également bi-directionnel.

2017-06-07 12:59 UTC, Gandus10 commented
Si travis passe, c'est bon !

2017-06-07 18:08 UTC, closed without merging