Gab branch
HE-Arc/livre-python pull request #152
Opened 2017-06-08 06:46 UTC by gaboss222

Update readme + resolve some todo

2017-06-08 07:40 UTC, greut commented
`func:carr\xe9`

```python
>>> "é".encode("utf-8")     
b'\xc3\xa9'                 
>>> "é".encode("cp1252")                                                                                         
b'\xe9
```

2017-06-08 10:37 UTC, greut commented on source/math/examples/Complexes.py
> +"""Exemple calculs mathématique en utilisant des nombres complexes."""
le _s_ était bien.

2017-06-08 10:38 UTC, greut commented on source/math/index.rst
> +======================
laissez tel que c'était.

2017-06-08 10:38 UTC, greut commented on source/math/index.rst
> + * `complex` pour les nombres complexes.
Est-ce que vallait vraiment la peine que j'effectue des corrections si vous balancez tout?

2017-06-08 10:57 UTC, greut commented
Merci de ne pas casser ce qui a été fait là: 8015a4a3775322b8541fb69615cb6f11587e3247

Dans le doute, recréez une nouvelle branche à partir d'`origin/master`.

2017-06-08 18:38 UTC, greut commented on source/math/index.rst
> -.. pourquoi sqrt et pow quand on a l'opérateur `**` ?
!

2017-06-08 18:40 UTC, greut commented on source/math/index.rst
> +.. - Nombres trigonométriques : <https://docs.python.org/2/library/math.html#trigonometric-functions>`
À faire avec des liens intersphinx qui pointeront vers la doc 3.

2017-06-08 18:41 UTC, greut commented on source/math/index.rst
> +    Math/Fractions
merci de conserver la mise en page telle que corrigée par moi.

2017-06-08 18:41 UTC, greut requested changes
Conservez la mise en page .

2017-06-10 12:39 UTC, greut commented on source/math/index.rst
>  Dans cet exemple, comme aucune des variables ne possède de virgule, Python les reconnait comme des *int*.
_virgule_ ?

2017-06-10 12:40 UTC, greut commented on source/math/index.rst
> +	False
Est-ce le résultat attendu?

2017-06-10 12:41 UTC, greut commented on source/math/index.rst
> +Cela signifie que 1 + 1/2 + 1/9 + 1/234 = 21/13
http://www.sphinx-doc.org/en/stable/ext/math.html

2017-06-10 12:41 UTC, greut commented on source/math/index.rst
> +.. _Math: https://docs.python.org/3/library/math.html?highlight=math#module-math
lien intersphinx seulement.

2017-06-10 13:01 UTC, gaboss222 commented on source/math/index.rst
> +	False
Non, pour avoir une égalité, il faudrait utiliser round() pour spécifier le nombre de décimale voulue 
round(tan(pi/4), 3) == 1
True

2017-06-10 14:04 UTC, gaboss222 commented on source/math/index.rst
> +.. _Math: https://docs.python.org/3/library/math.html?highlight=math#module-math
Pour lier aux modules, on utilise :py:mod: ? 
:py:func:`math.ceil` lien OK
:py:mod:`module-math` lien KO ...

2017-06-10 14:05 UTC, gaboss222 commented on source/math/index.rst
> +.. _Math: https://docs.python.org/3/library/math.html?highlight=math#module-math
Et même avec un 
intersphinx_mapping = {'python': ('https://docs.python.org/3.6', None)}

Je ne comprends pas comment lier au module math

2017-06-10 14:07 UTC, gaboss222 commented on source/math/index.rst
> +.. _Math: https://docs.python.org/3/library/math.html?highlight=math#module-math
C'est OK en fait,

2017-06-10 14:54 UTC, greut commented on source/math/index.rst
> +	False
non plus.

2017-06-10 14:55 UTC, greut commented on source/math/index.rst
> +	False
!google comment comparer deux `float`

2017-06-10 17:24 UTC, greut commented on source/math/index.rst
>  	True
:+1: n'hésitez pas à expliquer votre découverte du soir.

2017-06-11 15:32 UTC, greut commented on source/math/index.rst
> +La fonction ``isclose(a, b)`` Nous permet de comparer deux nombres en retournant *True* si ces derniers sont relativement proches l'un de l'autre.
à minima, un lien _intersphinx_

2017-06-11 15:54 UTC, greut commented on source/math/index.rst
> +La fonction :py:func:`isclose(a, b) <math.isclose>` Nous permet de comparer deux nombres en retournant *True* si ces derniers sont relativement proches l'un de l'autre.
:+1:!

2017-06-11 15:56 UTC, greut commented on source/math/index.rst
> +	False
Aha, bien essayé mais c'est de la triche. En suivant les exemples ci-dessus, on aimerait voir ceci.

```
>>> isfinite(1/0)
False
```

**NB** c'est possible mais pas de manière aussi directe.

2017-06-11 15:57 UTC, greut commented on source/math/index.rst
>  Elles s'expriment toutes sous la forme ``sin(x)``, ``cos(x)``, ``tan(x)`` et renvoient le sinus, cosinus et tangante de *x* en radians.
la _tangente_

2017-06-11 16:01 UTC, greut commented on source/math/index.rst
> +Le résultat, pour :math:`21/13` est : :math:`1 + 1/ 2 + 1/9 + 1/234`
Et c'est joli? Essayez ceci:

    $\frac{1}{2}$

2017-06-11 16:03 UTC, greut commented on source/math/index.rst
> +:py:mod:`math`
À ce stade, ça semble inutile de placer un lien de manière _random_ ici.

2017-06-11 16:03 UTC, greut commented on source/unittest/examples/carre.py
> +# endfunc:carré
il n'est pas à vous ce fichier??

2017-06-11 16:12 UTC, greut commented on source/unittest/examples/carre.py
> +# endfunc:carré
```
$ git checkout 708de252c39 source/unittest/examples/carre.py
```

2017-06-11 18:00 UTC, greut commented on source/math/index.rst
> +	False
En allant moins loin que `numpy`, c'est également possible.

```python
>>> decimal.setcontext(decimal.ExtendedContext)
>>> math.isfinite(decimal.Decimal('1') / decimal.Decimal('0'))
False
```

https://docs.python.org/3/library/decimal.html

2017-06-11 18:00 UTC, greut commented on source/math/index.rst
> +	False
⚠️ tabulation.

2017-06-11 20:14 UTC, greut commented on source/math/index.rst
> +	>>> from decimal import setcontext, ExtendedContext, Decimal
tabulation.

2017-06-11 20:14 UTC, greut commented on source/math/index.rst
> +    >>> isfinite(Decimal('1')/Decimal('0')
il manque une `)`

2017-06-11 20:17 UTC, greut commented on source/math/index.rst
> +    True
je ne suis pas forcément certain que de monter une comparaison avec `==` entre deux `float` soit utile. Surtout, si vous avez viré `frexp`. Égal, il y a une tabulation vers `pi`.

2017-06-12 06:43 UTC, greut requested changes
Restaurez les fichiers dans `unittest`

2017-06-12 06:43 UTC, greut commented on source/unittest/examples/carre.py
> +# endfunc:carré
@gaboss222 il reste à restaurer ce fichier et on est bon!

2017-06-12 08:51 UTC, greut approved these changes

2017-06-12 08:53 UTC, merged